dialogflow-api:
  image:
    repository: joachimprinzbach/dialogflow-api
    tag: v0.2.0
  network:
    http:
      servicePort: 8080
      ingress:
        host: dialogflow-api.apps.okd.baloise.dev
  env:
    - name: GIT_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: dialogflow-api-github-token