apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dialogflow-api-github-token
  namespace: dialogflow-api
spec:
  encryptedData:
    token: AgAk8FGF8b9XrbftVWbWa3C9+YJ5oP59qHBrlvbFuw54nvgzbEIfILOs16j3IvqawvYPKNS3y0BSnE2T6fR2bPEWcMM4U3/IminWsDGDLiY+hnl259ZUH1eM47hDcSJ40OtDCyabGfnSExagA9zDqwRXaVIeS0mygHedlBlSnCSSX5C95HOWw37Irg+76aPB1unfWVnyw4qT06B2AnNs5n66bpVz2scAOi+go1FxN/sWizwcfOdv5WO/q+DPkEWV0eZDyNANwt1OxVqyNBrRfh7Pej5DbwkxleBJmR4w1V2dDAV4zxvnRs+2KQKZx/J2mh5W2XZhRUldPSJuQNgokdFGsnLZB4UcrycbQQ+irLV4mo/WDn0r+2UDfv1/qKor+oC1FT8AmvG92AcucF+uyba9UPeeXm5nJ3qUj7YeKYhF+7Cft1vO1dQbBF7TtSkLthE+VwggId4yleX5RbWe+eUBjIRBH31TF2AptKbQQ3onTYg47y0PVf6Tm+TbyV7sjNLKtCIOtisZi6r3+gFsxXeYITb2H0Go6+6oEo/cSEHeAGLz+E3lyOMCqDRaUpTSPQcelkigDi/S2PGWWJHP24e4vOuRxSpw8WuRlJIs8C0lCEicgDrhLqHN2mZcAGge+I8CMhnigPYmK8gFnFrCvoU9k+/YLbd6/D8UcZPPMY+k6DX5a8eWOJy0wr913vdbfQvGHwucKkmGTgZ3MFNmQcpMp6gKQ9Jmky0id9JNO4Y0teqpUcP6envJ
  template:
    metadata:
      creationTimestamp: null
      name: dialogflow-api-github-token
      namespace: dialogflow-api

