pizza-inventory-service:
  image:
    repository: joachimprinzbach/pizza-inventory
    tag: 14
  ingress:
    enabled: true
    host: joachim-pizza-inventory-prod.apps.okd.baloise.dev
  env:
    - name: env
      value: "prod"