apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: pizza
spec:
  hosts:
    - "*"
  gateways:
    - pizza-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: pizza-inventory-service
            port:
              number: 80