pizza-order-service:
  image:
    repository: joachimprinzbach/pizza-order
    tag: 14
  ingress:
    enabled: true
    host: joachim-pizza-order-test.apps.origin.baloise.dev
  annotations:
    sidecar.istio.io/inject: "true"
  env:
    - name: env
      value: "test"
