apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "istio.name" . }}
spec:
  selector:
    istio: {{ .Values.ingressGateway }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"