{{ range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
    name: {{ .name }}
    labels:
        app: {{ .name }}
        chart: {{ template "istio.chart" $ }}
        release: {{ $.Release.Name }}
        heritage: {{ $.Release.Service }}
spec:
    type: {{ default "ClusterIP" .type }}
    ports:
        - port: {{ .port }}
          targetPort: {{ .port }}
          name: http
    selector:
        app: {{ default .name .appName }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .name }}
spec:
{{- if .gateway}}
  hosts:
    - "*"
  gateways:
  - {{ template "istio.name" $ }}
{{- else }}
  hosts:
    - "{{ .name }}"
{{- end }}
  http:
{{- $service := .}}
{{- range $service.versions }}
{{- if .match }}
    - match:
{{ toYaml .match | indent 8 }}
{{- end }}
      route:
          - destination:
              host: {{ $service.name }}
              subset: {{ .name }}
              port:
                number: {{ $service.port }}
{{- if .weight }}
            weight: {{ .weight }}
{{- end }}
{{- end }}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .name }}
spec:
  host: {{ .name }}
  subsets:
{{- range .versions }}
    - name: {{ .name }}
      labels:
        version: {{ .name }}
{{- end }}
{{- end }}